Predictor:
  Model:
    classpath: impact_reg_konfai.models.fireants:RegistrationNet
    RegistrationNet:
      scales:
      - 4
      - 2
      - 1
      affine_iterations:
      - 200
      - 100
      - 50
      deformable_iterations:
      - 200
      - 100
      - 50
      cc_kernel: 5
      affine_metric: mi
      affine_lr: 0.0
      deformable_method: syn
      deformable_metric: impact
      deformable_lr: 0.25
      integrator_n: 10
      smooth_warp_sigma: 1.0
      smooth_grad_sigma: 1.5
      seed: 42
      models:
        '0':
          ref: VBoussot/impact-torchscript-models:TS/M291.pt
          layers_mask: '01'
          layers_weight: 1.0
          pca: 0
          distance: L1
      outputs_criterions: None
  Dataset:
    groups_src:
      Volume_0:
        groups_dest:
          Fixed:
            transforms:
              TensorCast:
                dtype: float32
                inverse: false
            patch_transforms: None
            is_input: true
      Volume_1:
        groups_dest:
          Moving:
            transforms:
              TensorCast:
                dtype: float32
                inverse: false
            patch_transforms: None
            is_input: true
      Volume_2:
        groups_dest:
          FixedMask:
            transforms:
              TensorCast:
                dtype: float32
                inverse: false
            patch_transforms: None
            is_input: true
      Volume_3:
        groups_dest:
          MovingMask:
            transforms:
              TensorCast:
                dtype: float32
                inverse: false
            patch_transforms: None
            is_input: true
    augmentations:
      DataAugmentation_0:
        data_augmentations:
          Flip:
            f_prob:
            - 0
            - 0.5
            - 0.5
            vector_field: true
            prob: 1
        nb: 2
    Patch:
      patch_size: None
      overlap: None
      pad_value: None
      extend_slice: 0
    subset: None
    filter: None
    dataset_filenames:
    - ./Dataset/:mha
    use_cache: false
    batch_size: 1
    num_workers: None
    pin_memory: false
    prefetch_factor: None
    persistent_workers: None
  outputs_dataset:
    DisplacementField:
      OutputDataset:
        name_class: OutSameAsGroupDataset
        before_reduction_transforms: None
        after_reduction_transforms: None
        final_transforms:
          TensorCast:
            dtype: float32
            inverse: false
        dataset_filename: Transform:itktransform
        group: Transform
        same_as_group: Volume_0:Fixed
        patch_combine: None
        inverse_transform: false
        reduction: Mean
        Mean: {}
  train_name: ImpactReg-FireANTs-IMPACT
  manual_seed: 42
  gpu_checkpoints: None
  images_log: None
  combine: Mean
  autocast: false
  data_log: None
